modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"

[[mods]] #mandatory

modId="onyxarcanix" #mandatory
version="1.0" #mandatory
displayName="Onyx Arcanix" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
logoFile="examplemod.png" #optional
credits="Me" #optional
authors="BrownBear85" #optional
description='''
    A magic mod by BrownBear85

    My first forge mod
'''